### ISSUE TITLE
Update actions-find-and-replace-string and setOutput command

### ISSUE THREAD

**Issue by Rooarii** [govpf/openfisca-pf#62]
Iaorana 👋🏼 🌴 🌊 🇵🇫 

I can't submit a PR due to authorization aspects, therefore i open an issue with the description and changes i wanted to submit 😉 

The docker-image.yml file seems to have deprecated command such as set-output 
See [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

Deprecated message from actions
![Screenshot from 2023-03-04 16-19-45](https://user-images.githubusercontent.com/49068774/222914399-ed1b8d7a-d342-4e24-afec-40c3f3d7a243.png)

### Here is what I did:
Upgrade the `.github/workflows/docker-image.yml`
line 52
`      uses: mad9000/actions-find-and-replace-string@3
`
line 99
`
      run: echo "##[name=tag;]$(echo ${GITHUB_REF#refs/tags/} ${GITHUB_OUTPUT})"
`
### Here is what I expected to happen:
I have tested the updated github actions and tested it locally with [nektos/act](https://github.com/nektos/act)

result
![Screenshot from 2023-03-04 16-15-22](https://user-images.githubusercontent.com/49068774/222914132-fa1d8a23-35c9-4b3f-a5d1-55c8897f11e8.png)

**Comment by masterbox** [comment]
Hi,
Thank you !
@AlexisDefranoux  and @atouboulic could you have a look ?

**Comment by atouboulic** [comment]
Ia orana Rooarii,

Thank you for submitting your issue.
It has been fixed today and merged on master : https://github.com/govpf/openfisca-pf/pull/65

Best regards !!
